// Code generated by ent, DO NOT EDIT.

package signature

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldDeletedAt, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldValue, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldHash, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldModel, v))
}

// UseCount applies equality check predicate on the "use_count" field. It's identical to UseCountEQ.
func UseCount(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldUseCount, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastVerifiedAt applies equality check predicate on the "last_verified_at" field. It's identical to LastVerifiedAtEQ.
func LastVerifiedAt(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldLastVerifiedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldNotes, v))
}

// CollectedFromAccountID applies equality check predicate on the "collected_from_account_id" field. It's identical to CollectedFromAccountIDEQ.
func CollectedFromAccountID(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldCollectedFromAccountID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Signature {
	return predicate.Signature(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Signature {
	return predicate.Signature(sql.FieldNotNull(FieldDeletedAt))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContainsFold(FieldValue, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContainsFold(FieldHash, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.Signature {
	return predicate.Signature(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.Signature {
	return predicate.Signature(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContainsFold(FieldModel, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldSource, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldStatus, vs...))
}

// UseCountEQ applies the EQ predicate on the "use_count" field.
func UseCountEQ(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldUseCount, v))
}

// UseCountNEQ applies the NEQ predicate on the "use_count" field.
func UseCountNEQ(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldUseCount, v))
}

// UseCountIn applies the In predicate on the "use_count" field.
func UseCountIn(vs ...int64) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldUseCount, vs...))
}

// UseCountNotIn applies the NotIn predicate on the "use_count" field.
func UseCountNotIn(vs ...int64) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldUseCount, vs...))
}

// UseCountGT applies the GT predicate on the "use_count" field.
func UseCountGT(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldUseCount, v))
}

// UseCountGTE applies the GTE predicate on the "use_count" field.
func UseCountGTE(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldUseCount, v))
}

// UseCountLT applies the LT predicate on the "use_count" field.
func UseCountLT(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldUseCount, v))
}

// UseCountLTE applies the LTE predicate on the "use_count" field.
func UseCountLTE(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldUseCount, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.Signature {
	return predicate.Signature(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.Signature {
	return predicate.Signature(sql.FieldNotNull(FieldLastUsedAt))
}

// LastVerifiedAtEQ applies the EQ predicate on the "last_verified_at" field.
func LastVerifiedAtEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldLastVerifiedAt, v))
}

// LastVerifiedAtNEQ applies the NEQ predicate on the "last_verified_at" field.
func LastVerifiedAtNEQ(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldLastVerifiedAt, v))
}

// LastVerifiedAtIn applies the In predicate on the "last_verified_at" field.
func LastVerifiedAtIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldLastVerifiedAt, vs...))
}

// LastVerifiedAtNotIn applies the NotIn predicate on the "last_verified_at" field.
func LastVerifiedAtNotIn(vs ...time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldLastVerifiedAt, vs...))
}

// LastVerifiedAtGT applies the GT predicate on the "last_verified_at" field.
func LastVerifiedAtGT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldLastVerifiedAt, v))
}

// LastVerifiedAtGTE applies the GTE predicate on the "last_verified_at" field.
func LastVerifiedAtGTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldLastVerifiedAt, v))
}

// LastVerifiedAtLT applies the LT predicate on the "last_verified_at" field.
func LastVerifiedAtLT(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldLastVerifiedAt, v))
}

// LastVerifiedAtLTE applies the LTE predicate on the "last_verified_at" field.
func LastVerifiedAtLTE(v time.Time) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldLastVerifiedAt, v))
}

// LastVerifiedAtIsNil applies the IsNil predicate on the "last_verified_at" field.
func LastVerifiedAtIsNil() predicate.Signature {
	return predicate.Signature(sql.FieldIsNull(FieldLastVerifiedAt))
}

// LastVerifiedAtNotNil applies the NotNil predicate on the "last_verified_at" field.
func LastVerifiedAtNotNil() predicate.Signature {
	return predicate.Signature(sql.FieldNotNull(FieldLastVerifiedAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Signature {
	return predicate.Signature(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Signature {
	return predicate.Signature(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Signature {
	return predicate.Signature(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Signature {
	return predicate.Signature(sql.FieldContainsFold(FieldNotes, v))
}

// CollectedFromAccountIDEQ applies the EQ predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDEQ(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldEQ(FieldCollectedFromAccountID, v))
}

// CollectedFromAccountIDNEQ applies the NEQ predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDNEQ(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldNEQ(FieldCollectedFromAccountID, v))
}

// CollectedFromAccountIDIn applies the In predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDIn(vs ...int64) predicate.Signature {
	return predicate.Signature(sql.FieldIn(FieldCollectedFromAccountID, vs...))
}

// CollectedFromAccountIDNotIn applies the NotIn predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDNotIn(vs ...int64) predicate.Signature {
	return predicate.Signature(sql.FieldNotIn(FieldCollectedFromAccountID, vs...))
}

// CollectedFromAccountIDGT applies the GT predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDGT(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldGT(FieldCollectedFromAccountID, v))
}

// CollectedFromAccountIDGTE applies the GTE predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDGTE(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldGTE(FieldCollectedFromAccountID, v))
}

// CollectedFromAccountIDLT applies the LT predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDLT(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldLT(FieldCollectedFromAccountID, v))
}

// CollectedFromAccountIDLTE applies the LTE predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDLTE(v int64) predicate.Signature {
	return predicate.Signature(sql.FieldLTE(FieldCollectedFromAccountID, v))
}

// CollectedFromAccountIDIsNil applies the IsNil predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDIsNil() predicate.Signature {
	return predicate.Signature(sql.FieldIsNull(FieldCollectedFromAccountID))
}

// CollectedFromAccountIDNotNil applies the NotNil predicate on the "collected_from_account_id" field.
func CollectedFromAccountIDNotNil() predicate.Signature {
	return predicate.Signature(sql.FieldNotNull(FieldCollectedFromAccountID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Signature) predicate.Signature {
	return predicate.Signature(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Signature) predicate.Signature {
	return predicate.Signature(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Signature) predicate.Signature {
	return predicate.Signature(sql.NotPredicates(p))
}
