// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/signature"
)

// SignatureUpdate is the builder for updating Signature entities.
type SignatureUpdate struct {
	config
	hooks    []Hook
	mutation *SignatureMutation
}

// Where appends a list predicates to the SignatureUpdate builder.
func (_u *SignatureUpdate) Where(ps ...predicate.Signature) *SignatureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SignatureUpdate) SetUpdatedAt(v time.Time) *SignatureUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SignatureUpdate) SetDeletedAt(v time.Time) *SignatureUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableDeletedAt(v *time.Time) *SignatureUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SignatureUpdate) ClearDeletedAt() *SignatureUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetValue sets the "value" field.
func (_u *SignatureUpdate) SetValue(v string) *SignatureUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableValue(v *string) *SignatureUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *SignatureUpdate) SetHash(v string) *SignatureUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableHash(v *string) *SignatureUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *SignatureUpdate) SetModel(v string) *SignatureUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableModel(v *string) *SignatureUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *SignatureUpdate) ClearModel() *SignatureUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetSource sets the "source" field.
func (_u *SignatureUpdate) SetSource(v signature.Source) *SignatureUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableSource(v *signature.Source) *SignatureUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SignatureUpdate) SetStatus(v signature.Status) *SignatureUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableStatus(v *signature.Status) *SignatureUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUseCount sets the "use_count" field.
func (_u *SignatureUpdate) SetUseCount(v int64) *SignatureUpdate {
	_u.mutation.ResetUseCount()
	_u.mutation.SetUseCount(v)
	return _u
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableUseCount(v *int64) *SignatureUpdate {
	if v != nil {
		_u.SetUseCount(*v)
	}
	return _u
}

// AddUseCount adds value to the "use_count" field.
func (_u *SignatureUpdate) AddUseCount(v int64) *SignatureUpdate {
	_u.mutation.AddUseCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *SignatureUpdate) SetLastUsedAt(v time.Time) *SignatureUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableLastUsedAt(v *time.Time) *SignatureUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *SignatureUpdate) ClearLastUsedAt() *SignatureUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_u *SignatureUpdate) SetLastVerifiedAt(v time.Time) *SignatureUpdate {
	_u.mutation.SetLastVerifiedAt(v)
	return _u
}

// SetNillableLastVerifiedAt sets the "last_verified_at" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableLastVerifiedAt(v *time.Time) *SignatureUpdate {
	if v != nil {
		_u.SetLastVerifiedAt(*v)
	}
	return _u
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (_u *SignatureUpdate) ClearLastVerifiedAt() *SignatureUpdate {
	_u.mutation.ClearLastVerifiedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SignatureUpdate) SetNotes(v string) *SignatureUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableNotes(v *string) *SignatureUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SignatureUpdate) ClearNotes() *SignatureUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetCollectedFromAccountID sets the "collected_from_account_id" field.
func (_u *SignatureUpdate) SetCollectedFromAccountID(v int64) *SignatureUpdate {
	_u.mutation.ResetCollectedFromAccountID()
	_u.mutation.SetCollectedFromAccountID(v)
	return _u
}

// SetNillableCollectedFromAccountID sets the "collected_from_account_id" field if the given value is not nil.
func (_u *SignatureUpdate) SetNillableCollectedFromAccountID(v *int64) *SignatureUpdate {
	if v != nil {
		_u.SetCollectedFromAccountID(*v)
	}
	return _u
}

// AddCollectedFromAccountID adds value to the "collected_from_account_id" field.
func (_u *SignatureUpdate) AddCollectedFromAccountID(v int64) *SignatureUpdate {
	_u.mutation.AddCollectedFromAccountID(v)
	return _u
}

// ClearCollectedFromAccountID clears the value of the "collected_from_account_id" field.
func (_u *SignatureUpdate) ClearCollectedFromAccountID() *SignatureUpdate {
	_u.mutation.ClearCollectedFromAccountID()
	return _u
}

// Mutation returns the SignatureMutation object of the builder.
func (_u *SignatureUpdate) Mutation() *SignatureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SignatureUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignatureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SignatureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignatureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SignatureUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if signature.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized signature.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := signature.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SignatureUpdate) check() error {
	if v, ok := _u.mutation.Value(); ok {
		if err := signature.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Signature.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := signature.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Signature.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := signature.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Signature.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := signature.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Signature.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := signature.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Signature.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SignatureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signature.Table, signature.Columns, sqlgraph.NewFieldSpec(signature.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(signature.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(signature.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(signature.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(signature.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(signature.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(signature.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(signature.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(signature.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(signature.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UseCount(); ok {
		_spec.SetField(signature.FieldUseCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUseCount(); ok {
		_spec.AddField(signature.FieldUseCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(signature.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(signature.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastVerifiedAt(); ok {
		_spec.SetField(signature.FieldLastVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastVerifiedAtCleared() {
		_spec.ClearField(signature.FieldLastVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(signature.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(signature.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CollectedFromAccountID(); ok {
		_spec.SetField(signature.FieldCollectedFromAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCollectedFromAccountID(); ok {
		_spec.AddField(signature.FieldCollectedFromAccountID, field.TypeInt64, value)
	}
	if _u.mutation.CollectedFromAccountIDCleared() {
		_spec.ClearField(signature.FieldCollectedFromAccountID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SignatureUpdateOne is the builder for updating a single Signature entity.
type SignatureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignatureMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SignatureUpdateOne) SetUpdatedAt(v time.Time) *SignatureUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SignatureUpdateOne) SetDeletedAt(v time.Time) *SignatureUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableDeletedAt(v *time.Time) *SignatureUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SignatureUpdateOne) ClearDeletedAt() *SignatureUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetValue sets the "value" field.
func (_u *SignatureUpdateOne) SetValue(v string) *SignatureUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableValue(v *string) *SignatureUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *SignatureUpdateOne) SetHash(v string) *SignatureUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableHash(v *string) *SignatureUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *SignatureUpdateOne) SetModel(v string) *SignatureUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableModel(v *string) *SignatureUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *SignatureUpdateOne) ClearModel() *SignatureUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetSource sets the "source" field.
func (_u *SignatureUpdateOne) SetSource(v signature.Source) *SignatureUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableSource(v *signature.Source) *SignatureUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SignatureUpdateOne) SetStatus(v signature.Status) *SignatureUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableStatus(v *signature.Status) *SignatureUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUseCount sets the "use_count" field.
func (_u *SignatureUpdateOne) SetUseCount(v int64) *SignatureUpdateOne {
	_u.mutation.ResetUseCount()
	_u.mutation.SetUseCount(v)
	return _u
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableUseCount(v *int64) *SignatureUpdateOne {
	if v != nil {
		_u.SetUseCount(*v)
	}
	return _u
}

// AddUseCount adds value to the "use_count" field.
func (_u *SignatureUpdateOne) AddUseCount(v int64) *SignatureUpdateOne {
	_u.mutation.AddUseCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *SignatureUpdateOne) SetLastUsedAt(v time.Time) *SignatureUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableLastUsedAt(v *time.Time) *SignatureUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *SignatureUpdateOne) ClearLastUsedAt() *SignatureUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_u *SignatureUpdateOne) SetLastVerifiedAt(v time.Time) *SignatureUpdateOne {
	_u.mutation.SetLastVerifiedAt(v)
	return _u
}

// SetNillableLastVerifiedAt sets the "last_verified_at" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableLastVerifiedAt(v *time.Time) *SignatureUpdateOne {
	if v != nil {
		_u.SetLastVerifiedAt(*v)
	}
	return _u
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (_u *SignatureUpdateOne) ClearLastVerifiedAt() *SignatureUpdateOne {
	_u.mutation.ClearLastVerifiedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SignatureUpdateOne) SetNotes(v string) *SignatureUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableNotes(v *string) *SignatureUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SignatureUpdateOne) ClearNotes() *SignatureUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetCollectedFromAccountID sets the "collected_from_account_id" field.
func (_u *SignatureUpdateOne) SetCollectedFromAccountID(v int64) *SignatureUpdateOne {
	_u.mutation.ResetCollectedFromAccountID()
	_u.mutation.SetCollectedFromAccountID(v)
	return _u
}

// SetNillableCollectedFromAccountID sets the "collected_from_account_id" field if the given value is not nil.
func (_u *SignatureUpdateOne) SetNillableCollectedFromAccountID(v *int64) *SignatureUpdateOne {
	if v != nil {
		_u.SetCollectedFromAccountID(*v)
	}
	return _u
}

// AddCollectedFromAccountID adds value to the "collected_from_account_id" field.
func (_u *SignatureUpdateOne) AddCollectedFromAccountID(v int64) *SignatureUpdateOne {
	_u.mutation.AddCollectedFromAccountID(v)
	return _u
}

// ClearCollectedFromAccountID clears the value of the "collected_from_account_id" field.
func (_u *SignatureUpdateOne) ClearCollectedFromAccountID() *SignatureUpdateOne {
	_u.mutation.ClearCollectedFromAccountID()
	return _u
}

// Mutation returns the SignatureMutation object of the builder.
func (_u *SignatureUpdateOne) Mutation() *SignatureMutation {
	return _u.mutation
}

// Where appends a list predicates to the SignatureUpdate builder.
func (_u *SignatureUpdateOne) Where(ps ...predicate.Signature) *SignatureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SignatureUpdateOne) Select(field string, fields ...string) *SignatureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Signature entity.
func (_u *SignatureUpdateOne) Save(ctx context.Context) (*Signature, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignatureUpdateOne) SaveX(ctx context.Context) *Signature {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SignatureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignatureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SignatureUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if signature.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized signature.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := signature.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SignatureUpdateOne) check() error {
	if v, ok := _u.mutation.Value(); ok {
		if err := signature.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Signature.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := signature.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Signature.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := signature.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Signature.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := signature.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Signature.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := signature.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Signature.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SignatureUpdateOne) sqlSave(ctx context.Context) (_node *Signature, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signature.Table, signature.Columns, sqlgraph.NewFieldSpec(signature.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Signature.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signature.FieldID)
		for _, f := range fields {
			if !signature.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signature.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(signature.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(signature.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(signature.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(signature.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(signature.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(signature.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(signature.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(signature.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(signature.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UseCount(); ok {
		_spec.SetField(signature.FieldUseCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUseCount(); ok {
		_spec.AddField(signature.FieldUseCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(signature.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(signature.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastVerifiedAt(); ok {
		_spec.SetField(signature.FieldLastVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastVerifiedAtCleared() {
		_spec.ClearField(signature.FieldLastVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(signature.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(signature.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CollectedFromAccountID(); ok {
		_spec.SetField(signature.FieldCollectedFromAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCollectedFromAccountID(); ok {
		_spec.AddField(signature.FieldCollectedFromAccountID, field.TypeInt64, value)
	}
	if _u.mutation.CollectedFromAccountIDCleared() {
		_spec.ClearField(signature.FieldCollectedFromAccountID, field.TypeInt64)
	}
	_node = &Signature{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
