// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/signature"
)

// SignatureCreate is the builder for creating a Signature entity.
type SignatureCreate struct {
	config
	mutation *SignatureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SignatureCreate) SetCreatedAt(v time.Time) *SignatureCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableCreatedAt(v *time.Time) *SignatureCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SignatureCreate) SetUpdatedAt(v time.Time) *SignatureCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableUpdatedAt(v *time.Time) *SignatureCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SignatureCreate) SetDeletedAt(v time.Time) *SignatureCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableDeletedAt(v *time.Time) *SignatureCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *SignatureCreate) SetValue(v string) *SignatureCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetHash sets the "hash" field.
func (_c *SignatureCreate) SetHash(v string) *SignatureCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *SignatureCreate) SetModel(v string) *SignatureCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableModel(v *string) *SignatureCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *SignatureCreate) SetSource(v signature.Source) *SignatureCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableSource(v *signature.Source) *SignatureCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SignatureCreate) SetStatus(v signature.Status) *SignatureCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableStatus(v *signature.Status) *SignatureCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUseCount sets the "use_count" field.
func (_c *SignatureCreate) SetUseCount(v int64) *SignatureCreate {
	_c.mutation.SetUseCount(v)
	return _c
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableUseCount(v *int64) *SignatureCreate {
	if v != nil {
		_c.SetUseCount(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *SignatureCreate) SetLastUsedAt(v time.Time) *SignatureCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableLastUsedAt(v *time.Time) *SignatureCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_c *SignatureCreate) SetLastVerifiedAt(v time.Time) *SignatureCreate {
	_c.mutation.SetLastVerifiedAt(v)
	return _c
}

// SetNillableLastVerifiedAt sets the "last_verified_at" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableLastVerifiedAt(v *time.Time) *SignatureCreate {
	if v != nil {
		_c.SetLastVerifiedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SignatureCreate) SetNotes(v string) *SignatureCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableNotes(v *string) *SignatureCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCollectedFromAccountID sets the "collected_from_account_id" field.
func (_c *SignatureCreate) SetCollectedFromAccountID(v int64) *SignatureCreate {
	_c.mutation.SetCollectedFromAccountID(v)
	return _c
}

// SetNillableCollectedFromAccountID sets the "collected_from_account_id" field if the given value is not nil.
func (_c *SignatureCreate) SetNillableCollectedFromAccountID(v *int64) *SignatureCreate {
	if v != nil {
		_c.SetCollectedFromAccountID(*v)
	}
	return _c
}

// Mutation returns the SignatureMutation object of the builder.
func (_c *SignatureCreate) Mutation() *SignatureMutation {
	return _c.mutation
}

// Save creates the Signature in the database.
func (_c *SignatureCreate) Save(ctx context.Context) (*Signature, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SignatureCreate) SaveX(ctx context.Context) *Signature {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignatureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignatureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SignatureCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if signature.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized signature.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := signature.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if signature.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized signature.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := signature.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := signature.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := signature.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		v := signature.DefaultUseCount
		_c.mutation.SetUseCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SignatureCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Signature.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Signature.updated_at"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Signature.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := signature.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Signature.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Signature.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := signature.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Signature.hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := signature.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Signature.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Signature.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := signature.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Signature.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Signature.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := signature.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Signature.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		return &ValidationError{Name: "use_count", err: errors.New(`ent: missing required field "Signature.use_count"`)}
	}
	return nil
}

func (_c *SignatureCreate) sqlSave(ctx context.Context) (*Signature, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SignatureCreate) createSpec() (*Signature, *sqlgraph.CreateSpec) {
	var (
		_node = &Signature{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signature.Table, sqlgraph.NewFieldSpec(signature.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(signature.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(signature.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(signature.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(signature.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(signature.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(signature.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(signature.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(signature.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UseCount(); ok {
		_spec.SetField(signature.FieldUseCount, field.TypeInt64, value)
		_node.UseCount = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(signature.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.LastVerifiedAt(); ok {
		_spec.SetField(signature.FieldLastVerifiedAt, field.TypeTime, value)
		_node.LastVerifiedAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(signature.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CollectedFromAccountID(); ok {
		_spec.SetField(signature.FieldCollectedFromAccountID, field.TypeInt64, value)
		_node.CollectedFromAccountID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Signature.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignatureUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SignatureCreate) OnConflict(opts ...sql.ConflictOption) *SignatureUpsertOne {
	_c.conflict = opts
	return &SignatureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Signature.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignatureCreate) OnConflictColumns(columns ...string) *SignatureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignatureUpsertOne{
		create: _c,
	}
}

type (
	// SignatureUpsertOne is the builder for "upsert"-ing
	//  one Signature node.
	SignatureUpsertOne struct {
		create *SignatureCreate
	}

	// SignatureUpsert is the "OnConflict" setter.
	SignatureUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SignatureUpsert) SetUpdatedAt(v time.Time) *SignatureUpsert {
	u.Set(signature.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateUpdatedAt() *SignatureUpsert {
	u.SetExcluded(signature.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SignatureUpsert) SetDeletedAt(v time.Time) *SignatureUpsert {
	u.Set(signature.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateDeletedAt() *SignatureUpsert {
	u.SetExcluded(signature.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SignatureUpsert) ClearDeletedAt() *SignatureUpsert {
	u.SetNull(signature.FieldDeletedAt)
	return u
}

// SetValue sets the "value" field.
func (u *SignatureUpsert) SetValue(v string) *SignatureUpsert {
	u.Set(signature.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateValue() *SignatureUpsert {
	u.SetExcluded(signature.FieldValue)
	return u
}

// SetHash sets the "hash" field.
func (u *SignatureUpsert) SetHash(v string) *SignatureUpsert {
	u.Set(signature.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateHash() *SignatureUpsert {
	u.SetExcluded(signature.FieldHash)
	return u
}

// SetModel sets the "model" field.
func (u *SignatureUpsert) SetModel(v string) *SignatureUpsert {
	u.Set(signature.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateModel() *SignatureUpsert {
	u.SetExcluded(signature.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *SignatureUpsert) ClearModel() *SignatureUpsert {
	u.SetNull(signature.FieldModel)
	return u
}

// SetSource sets the "source" field.
func (u *SignatureUpsert) SetSource(v signature.Source) *SignatureUpsert {
	u.Set(signature.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateSource() *SignatureUpsert {
	u.SetExcluded(signature.FieldSource)
	return u
}

// SetStatus sets the "status" field.
func (u *SignatureUpsert) SetStatus(v signature.Status) *SignatureUpsert {
	u.Set(signature.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateStatus() *SignatureUpsert {
	u.SetExcluded(signature.FieldStatus)
	return u
}

// SetUseCount sets the "use_count" field.
func (u *SignatureUpsert) SetUseCount(v int64) *SignatureUpsert {
	u.Set(signature.FieldUseCount, v)
	return u
}

// UpdateUseCount sets the "use_count" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateUseCount() *SignatureUpsert {
	u.SetExcluded(signature.FieldUseCount)
	return u
}

// AddUseCount adds v to the "use_count" field.
func (u *SignatureUpsert) AddUseCount(v int64) *SignatureUpsert {
	u.Add(signature.FieldUseCount, v)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *SignatureUpsert) SetLastUsedAt(v time.Time) *SignatureUpsert {
	u.Set(signature.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateLastUsedAt() *SignatureUpsert {
	u.SetExcluded(signature.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *SignatureUpsert) ClearLastUsedAt() *SignatureUpsert {
	u.SetNull(signature.FieldLastUsedAt)
	return u
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (u *SignatureUpsert) SetLastVerifiedAt(v time.Time) *SignatureUpsert {
	u.Set(signature.FieldLastVerifiedAt, v)
	return u
}

// UpdateLastVerifiedAt sets the "last_verified_at" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateLastVerifiedAt() *SignatureUpsert {
	u.SetExcluded(signature.FieldLastVerifiedAt)
	return u
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (u *SignatureUpsert) ClearLastVerifiedAt() *SignatureUpsert {
	u.SetNull(signature.FieldLastVerifiedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *SignatureUpsert) SetNotes(v string) *SignatureUpsert {
	u.Set(signature.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateNotes() *SignatureUpsert {
	u.SetExcluded(signature.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SignatureUpsert) ClearNotes() *SignatureUpsert {
	u.SetNull(signature.FieldNotes)
	return u
}

// SetCollectedFromAccountID sets the "collected_from_account_id" field.
func (u *SignatureUpsert) SetCollectedFromAccountID(v int64) *SignatureUpsert {
	u.Set(signature.FieldCollectedFromAccountID, v)
	return u
}

// UpdateCollectedFromAccountID sets the "collected_from_account_id" field to the value that was provided on create.
func (u *SignatureUpsert) UpdateCollectedFromAccountID() *SignatureUpsert {
	u.SetExcluded(signature.FieldCollectedFromAccountID)
	return u
}

// AddCollectedFromAccountID adds v to the "collected_from_account_id" field.
func (u *SignatureUpsert) AddCollectedFromAccountID(v int64) *SignatureUpsert {
	u.Add(signature.FieldCollectedFromAccountID, v)
	return u
}

// ClearCollectedFromAccountID clears the value of the "collected_from_account_id" field.
func (u *SignatureUpsert) ClearCollectedFromAccountID() *SignatureUpsert {
	u.SetNull(signature.FieldCollectedFromAccountID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Signature.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SignatureUpsertOne) UpdateNewValues() *SignatureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(signature.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Signature.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SignatureUpsertOne) Ignore() *SignatureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignatureUpsertOne) DoNothing() *SignatureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignatureCreate.OnConflict
// documentation for more info.
func (u *SignatureUpsertOne) Update(set func(*SignatureUpsert)) *SignatureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignatureUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SignatureUpsertOne) SetUpdatedAt(v time.Time) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateUpdatedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SignatureUpsertOne) SetDeletedAt(v time.Time) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateDeletedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SignatureUpsertOne) ClearDeletedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearDeletedAt()
	})
}

// SetValue sets the "value" field.
func (u *SignatureUpsertOne) SetValue(v string) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateValue() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateValue()
	})
}

// SetHash sets the "hash" field.
func (u *SignatureUpsertOne) SetHash(v string) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateHash() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateHash()
	})
}

// SetModel sets the "model" field.
func (u *SignatureUpsertOne) SetModel(v string) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateModel() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *SignatureUpsertOne) ClearModel() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearModel()
	})
}

// SetSource sets the "source" field.
func (u *SignatureUpsertOne) SetSource(v signature.Source) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateSource() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateSource()
	})
}

// SetStatus sets the "status" field.
func (u *SignatureUpsertOne) SetStatus(v signature.Status) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateStatus() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateStatus()
	})
}

// SetUseCount sets the "use_count" field.
func (u *SignatureUpsertOne) SetUseCount(v int64) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetUseCount(v)
	})
}

// AddUseCount adds v to the "use_count" field.
func (u *SignatureUpsertOne) AddUseCount(v int64) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.AddUseCount(v)
	})
}

// UpdateUseCount sets the "use_count" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateUseCount() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateUseCount()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *SignatureUpsertOne) SetLastUsedAt(v time.Time) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateLastUsedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *SignatureUpsertOne) ClearLastUsedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (u *SignatureUpsertOne) SetLastVerifiedAt(v time.Time) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetLastVerifiedAt(v)
	})
}

// UpdateLastVerifiedAt sets the "last_verified_at" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateLastVerifiedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateLastVerifiedAt()
	})
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (u *SignatureUpsertOne) ClearLastVerifiedAt() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearLastVerifiedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *SignatureUpsertOne) SetNotes(v string) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateNotes() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SignatureUpsertOne) ClearNotes() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearNotes()
	})
}

// SetCollectedFromAccountID sets the "collected_from_account_id" field.
func (u *SignatureUpsertOne) SetCollectedFromAccountID(v int64) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.SetCollectedFromAccountID(v)
	})
}

// AddCollectedFromAccountID adds v to the "collected_from_account_id" field.
func (u *SignatureUpsertOne) AddCollectedFromAccountID(v int64) *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.AddCollectedFromAccountID(v)
	})
}

// UpdateCollectedFromAccountID sets the "collected_from_account_id" field to the value that was provided on create.
func (u *SignatureUpsertOne) UpdateCollectedFromAccountID() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateCollectedFromAccountID()
	})
}

// ClearCollectedFromAccountID clears the value of the "collected_from_account_id" field.
func (u *SignatureUpsertOne) ClearCollectedFromAccountID() *SignatureUpsertOne {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearCollectedFromAccountID()
	})
}

// Exec executes the query.
func (u *SignatureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SignatureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignatureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SignatureUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SignatureUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SignatureCreateBulk is the builder for creating many Signature entities in bulk.
type SignatureCreateBulk struct {
	config
	err      error
	builders []*SignatureCreate
	conflict []sql.ConflictOption
}

// Save creates the Signature entities in the database.
func (_c *SignatureCreateBulk) Save(ctx context.Context) ([]*Signature, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Signature, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignatureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SignatureCreateBulk) SaveX(ctx context.Context) []*Signature {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignatureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignatureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Signature.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignatureUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SignatureCreateBulk) OnConflict(opts ...sql.ConflictOption) *SignatureUpsertBulk {
	_c.conflict = opts
	return &SignatureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Signature.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignatureCreateBulk) OnConflictColumns(columns ...string) *SignatureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignatureUpsertBulk{
		create: _c,
	}
}

// SignatureUpsertBulk is the builder for "upsert"-ing
// a bulk of Signature nodes.
type SignatureUpsertBulk struct {
	create *SignatureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Signature.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SignatureUpsertBulk) UpdateNewValues() *SignatureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(signature.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Signature.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SignatureUpsertBulk) Ignore() *SignatureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignatureUpsertBulk) DoNothing() *SignatureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignatureCreateBulk.OnConflict
// documentation for more info.
func (u *SignatureUpsertBulk) Update(set func(*SignatureUpsert)) *SignatureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignatureUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SignatureUpsertBulk) SetUpdatedAt(v time.Time) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateUpdatedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SignatureUpsertBulk) SetDeletedAt(v time.Time) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateDeletedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SignatureUpsertBulk) ClearDeletedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearDeletedAt()
	})
}

// SetValue sets the "value" field.
func (u *SignatureUpsertBulk) SetValue(v string) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateValue() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateValue()
	})
}

// SetHash sets the "hash" field.
func (u *SignatureUpsertBulk) SetHash(v string) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateHash() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateHash()
	})
}

// SetModel sets the "model" field.
func (u *SignatureUpsertBulk) SetModel(v string) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateModel() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *SignatureUpsertBulk) ClearModel() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearModel()
	})
}

// SetSource sets the "source" field.
func (u *SignatureUpsertBulk) SetSource(v signature.Source) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateSource() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateSource()
	})
}

// SetStatus sets the "status" field.
func (u *SignatureUpsertBulk) SetStatus(v signature.Status) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateStatus() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateStatus()
	})
}

// SetUseCount sets the "use_count" field.
func (u *SignatureUpsertBulk) SetUseCount(v int64) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetUseCount(v)
	})
}

// AddUseCount adds v to the "use_count" field.
func (u *SignatureUpsertBulk) AddUseCount(v int64) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.AddUseCount(v)
	})
}

// UpdateUseCount sets the "use_count" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateUseCount() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateUseCount()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *SignatureUpsertBulk) SetLastUsedAt(v time.Time) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateLastUsedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *SignatureUpsertBulk) ClearLastUsedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (u *SignatureUpsertBulk) SetLastVerifiedAt(v time.Time) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetLastVerifiedAt(v)
	})
}

// UpdateLastVerifiedAt sets the "last_verified_at" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateLastVerifiedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateLastVerifiedAt()
	})
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (u *SignatureUpsertBulk) ClearLastVerifiedAt() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearLastVerifiedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *SignatureUpsertBulk) SetNotes(v string) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateNotes() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SignatureUpsertBulk) ClearNotes() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearNotes()
	})
}

// SetCollectedFromAccountID sets the "collected_from_account_id" field.
func (u *SignatureUpsertBulk) SetCollectedFromAccountID(v int64) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.SetCollectedFromAccountID(v)
	})
}

// AddCollectedFromAccountID adds v to the "collected_from_account_id" field.
func (u *SignatureUpsertBulk) AddCollectedFromAccountID(v int64) *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.AddCollectedFromAccountID(v)
	})
}

// UpdateCollectedFromAccountID sets the "collected_from_account_id" field to the value that was provided on create.
func (u *SignatureUpsertBulk) UpdateCollectedFromAccountID() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.UpdateCollectedFromAccountID()
	})
}

// ClearCollectedFromAccountID clears the value of the "collected_from_account_id" field.
func (u *SignatureUpsertBulk) ClearCollectedFromAccountID() *SignatureUpsertBulk {
	return u.Update(func(s *SignatureUpsert) {
		s.ClearCollectedFromAccountID()
	})
}

// Exec executes the query.
func (u *SignatureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SignatureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SignatureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignatureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
